openapi: 3.0.0
info:
  title: Mentoria API
  description: This is the API documentation for the Mentoria platform - a mentorship platform connecting mentors and mentees.
  termsOfService: 'http://localhost:5173/terms/'
  contact:
    email: duonggiabao254@gmail.com
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
  version: 1.0.0
servers:
  - url: 'http://localhost:3000'
    description: Development server
  - url: 'https://api.mentoria.com'
    description: Production server
tags:
  - name: authentication
    description: User authentication and account management
  - name: oauth
    description: OAuth integration with third-party providers
paths:
  /api/auth/register:
    post:
      tags:
        - authentication
      summary: Register a new user
      description: 'Register a new user account. After registration, an OTP will be sent to the provided email for verification.'
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User registered successfully. OTP sent to email.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Validation errors or email already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/auth/verify-otp:
    post:
      tags:
        - authentication
      summary: Verify OTP
      description: 'Verify the OTP sent to user''s email after registration. Upon successful verification, user will be logged in automatically.'
      operationId: verifyOTP
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OTPRequest'
      responses:
        '200':
          description: OTP verified successfully. User is now logged in.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
          headers:
            Set-Cookie:
              description: JWT token set as HTTP-only cookie
              schema:
                type: string
        '400':
          description: Invalid or expired OTP
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/auth/login:
    post:
      tags:
        - authentication
      summary: User login
      description: Authenticate user with email and password. Returns JWT token as HTTP-only cookie.
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
          headers:
            Set-Cookie:
              description: JWT token set as HTTP-only cookie
              schema:
                type: string
        '400':
          description: Invalid credentials or validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/auth/logout:
    post:
      tags:
        - authentication
      summary: User logout
      description: Logout user and clear authentication cookie
      operationId: logoutUser
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '401':
          description: Unauthorized - user not logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/auth/forgot-password:
    post:
      tags:
        - authentication
      summary: Request password reset
      description: Send password reset email to user's registered email address
      operationId: forgotPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPasswordRequest'
      responses:
        '200':
          description: Reset password email sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '404':
          description: Email not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  '/api/auth/reset-password/{token}':
    post:
      tags:
        - authentication
      summary: Reset password
      description: Reset password using the token received in email
      operationId: resetPassword
      parameters:
        - name: token
          in: path
          required: true
          description: Password reset token from email
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
      responses:
        '200':
          description: Password reset successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Invalid token or validation errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/auth/me:
    get:
      tags:
        - authentication
      summary: Get current user info
      description: Get information about the currently authenticated user
      operationId: getMe
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User information retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  user:
                    $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized - user not logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/auth/google:
    get:
      tags:
        - oauth
      summary: Initiate Google OAuth
      description: Redirect to Google OAuth consent screen
      operationId: googleAuth
      responses:
        '302':
          description: Redirect to Google OAuth
        '500':
          description: OAuth configuration error
  /api/auth/google/callback:
    get:
      tags:
        - oauth
      summary: Google OAuth callback
      description: Handle Google OAuth callback and authenticate user
      operationId: googleCallback
      parameters:
        - name: code
          in: query
          description: Authorization code from Google
          schema:
            type: string
        - name: state
          in: query
          description: State parameter for CSRF protection
          schema:
            type: string
      responses:
        '302':
          description: Redirect to client with authentication status
          headers:
            Set-Cookie:
              description: JWT token set as HTTP-only cookie (on success)
              schema:
                type: string
        '400':
          description: OAuth authentication failed
components:
  schemas:
    RegisterRequest:
      type: object
      required:
        - firstName
        - lastName
        - email
        - password
      properties:
        firstName:
          type: string
          minLength: 1
          example: John
          description: User's first name
        lastName:
          type: string
          minLength: 1
          example: Doe
          description: User's last name
        email:
          type: string
          format: email
          example: john.doe@example.com
          description: User's email address (must be unique)
        password:
          type: string
          minLength: 3
          maxLength: 20
          example: securepassword123
          description: User's password (3-20 characters)
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: john.doe@example.com
          description: User's email address
        password:
          type: string
          example: securepassword123
          description: User's password
    OTPRequest:
      type: object
      required:
        - otp
      properties:
        otp:
          type: string
          example: '123456'
          description: 6-digit OTP code sent to user's email
    ForgotPasswordRequest:
      type: object
      required:
        - email
      properties:
        email:
          type: string
          format: email
          example: john.doe@example.com
          description: User's registered email address
    ResetPasswordRequest:
      type: object
      required:
        - newPassword
      properties:
        newPassword:
          type: string
          minLength: 3
          maxLength: 20
          example: newsecurepassword123
          description: New password (3-20 characters)
    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: Operation completed successfully
    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: Error occurred
    ValidationErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: Validation errors
        data:
          type: object
          properties:
            errors:
              type: array
              items:
                type: string
              example:
                - 'Email is invalid: email'
                - 'Password must be at least 3 characters long: password'
            oldData:
              type: object
              description: Previously submitted data (excluding sensitive fields like password)
              example:
                firstName: John
                lastName: Doe
                email: invalid-email
                password: ''
    User:
      type: object
      properties:
        user_id:
          type: string
          example: 123e4567-e89b-12d3-a456-426614174000
          description: Unique user identifier
        firstName:
          type: string
          example: John
          description: User's first name
        lastName:
          type: string
          example: Doe
          description: User's last name
        email:
          type: string
          format: email
          example: john.doe@example.com
          description: User's email address
        role:
          type: string
          enum:
            - Mentee
            - Mentor
            - Admin
          example: Mentee
          description: User's role in the platform
        status:
          type: string
          enum:
            - Active
            - Banned
            - Pending
          example: Active
          description: User's account status
        provider:
          type: string
          enum:
            - Local
            - Google
          example: Local
          description: Authentication provider used
        created_at:
          type: string
          format: date-time
          example: '2023-10-25T10:30:00Z'
          description: Account creation timestamp
        updated_at:
          type: string
          format: date-time
          example: '2023-10-25T10:30:00Z'
          description: Last account update timestamp
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token obtained from login or OAuth. Token is sent as HTTP-only cookie named 'token'.
